### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by philipchang411** [philipchang411/MatrixTraversal#2]
- [ ]  Determine how to accurately calculate penalty
- [ ] How to make it dynamic programming
- [ ] How to resolve a tie in the max value in a column
- [ ] Reading in the input
- [ ] 
- [ ]
